In [1]:
import numpy as np

In [22]:
#numpy array

prices = np.array([100, 250, 80, 430, 175])

tax = 0.15

discount = 0.10

prices_with_tax = prices + (prices * tax)

prices_with_discount = prices - (prices * discount)

print("Prices with tax:", prices_with_tax)
print("Prices with discount:", prices_with_discount)
print("Mean price with discount:", prices_with_discount.mean())

Prices with tax: [115.   287.5   92.   494.5  201.25]
Prices with discount: [ 90.  225.   72.  387.  157.5]
Mean price with discount: 186.3


In [29]:
import numpy as np
import time

data = np.random.randint(1, 100, size=1_000_000)

#loop version
def loop_square(arr):
    result = []
    for x in arr:
        result.append(x ** 2)
    return result

#Numpy version
def numpy_square(arr):
    return arr ** 2

In [30]:
%timeit loop_square(data)
%timeit numpy_square(data)

216 ms ± 40.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
2.67 ms ± 1.27 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [32]:
# square the data in an array of 1 million integers

data = np.random.randint(1, 100, size=1_000_000)

squared_data = data ** 2

print(squared_data)

[4489 1444 1600 ... 2916 1521  784]


In [41]:
#mean of 1 million floata
floats = np.random.rand(1_000_000)

mean_value = floats.mean()

print("Mean of the floats:", mean_value)

Mean of the floats: 0.5001679154551125


In [45]:
# add two arrays of 1 million numbers element by element
array1 = np.random.randint(1, 100, size=1_000_000)
array2 = np.random.randint(1, 100, size=1_000_000)

result = array1 + array2

print(result)

[141 118  83 ... 123  27 135]


In [48]:
#numbers greater than 500

numbers = np.random.randint(1, 1000, size=1_000_000)

filtered_numbers = numbers[numbers > 500]
print(filtered_numbers)

[907 679 860 ... 700 731 923]


In [49]:
# array normalization
data = np.random.randint(1, 100, size=1_000_000)

data_sub = data - data.mean()

data_normalized = data_sub / data.std()

print(data_normalized)

[ 0.63011908  1.19007944 -1.18975207 ... -1.36473968  1.01509183
  1.71504227]
